from . import crm_lead
from . import crm_team
from . import crm_tag
from . import res_partner
from . import mail_message
from . import mail_activity
from . import hr_employee
from . import account_analytic
from . import account_move
from . import account_budget
from . import project_project
